### PR TITLE
import types, python lib

### PR DESCRIPTION
**Pull request by lucassimon**
this library is being used in function lower() on line 283

### CODE REVIEW

**Comment by eabg** [comment]
I do not see where you indicate use of that library, but that file is not used. previously used for StringTypes but support for python 2 and 3 were given and no longer imported directly from types.

**Comment by lucassimon** [comment]
[Here]( https://github.com/chrisglass/xhtml2pdf/blob/master/xhtml2pdf/parser.py#L282)

I updated this library, and I'm using with django_eay_pdf, and raise an exception in this line.

**Comment by eabg** [comment]
Someone carelessly code included with support for python 3, finish a change that solves the problem up. types is that the library does not behave the same in python 2 and 3.

**Comment by lucassimon** [comment]
thanks, to fix it

**Pull request closed without merging**
